### ISSUE TITLE
Runtimeerror: Invalid settings file [settings] 

### ISSUE THREAD

**Issue by DavisK-rgb** [notexactlyawe/abracadabra#29]
While running song_recognizer initialise, I get an error : Invalid settings file [settings]

**Comment by niemiaszek** [comment]
Hello @DavisK-rgb . Have you resolved this bug?

**Comment by notaSWE** [comment]
I am getting the same issue.  I installed simple_settings via pip and did zero configuration thereafter.

**Comment by tekchip** [comment]
Bump. Running into this when running: ` song_recogniser register file.mp3`

`Traceback (most recent call last):
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/abracadabra/storage.py", line 15, in get_cursor
    conn = sqlite3.connect(settings.DB_PATH, timeout=30)
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/simple_settings/core.py", line 94, in __getattr__
    self.setup()
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/simple_settings/core.py", line 68, in setup
    self._load_settings_pipeline()
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/simple_settings/core.py", line 75, in _load_settings_pipeline
    strategy = self._get_strategy_by_file(settings_file)
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/simple_settings/core.py", line 91, in _get_strategy_by_file
    raise RuntimeError('Invalid settings file [{}]'.format(settings_file))
RuntimeError: Invalid settings file [settings]`

Followed by:

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tekchip/abracadabra/bin/song_recogniser", line 33, in <module>
    sys.exit(load_entry_point('abracadabra==0.1', 'console_scripts', 'song_recogniser')())
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/abracadabra/scripts/song_recogniser.py", line 18, in register
    recog.register_song(path)
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/abracadabra/recognise.py", line 33, in register_song
    if song_in_db(filename):
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/abracadabra/storage.py", line 50, in song_in_db
    with get_cursor() as (conn, c):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/tekchip/abracadabra/lib/python3.10/site-packages/abracadabra/storage.py", line 18, in get_cursor
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment`

**Comment by tekchip** [comment]
Just managed to resolve at least this error via information here https://github.com/neulab/xnmt/issues/322

`export PYTHONPATH="/path/to/project/:$PYTHONPATH"`

This is followed by some sqlite errors but at least this one is resolved.

**Comment by tekchip** [comment]
Looks like the following sqlite errors are issues with path. Related to the path change in my previous comment. So it resolves one problem but causes another. Seems the path change sends sqlite one directory too deep. Not yet sure how to remediate the path discrepancy between simple_file and sqlite just yet.
