### ISSUE TITLE
Initilise not working

### ISSUE THREAD

**Issue by imsomdev** [notexactlyawe/abracadabra#42]
```
Traceback (most recent call last):
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/abracadabra/storage.py", line 15, in get_cursor
    conn = sqlite3.connect(settings.DB_PATH, timeout=30)
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/simple_settings/core.py", line 94, in __getattr__
    self.setup()
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/simple_settings/core.py", line 68, in setup
    self._load_settings_pipeline()
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/simple_settings/core.py", line 75, in _load_settings_pipeline
    strategy = self._get_strategy_by_file(settings_file)
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/simple_settings/core.py", line 91, in _get_strategy_by_file
    raise RuntimeError('Invalid settings file [{}]'.format(settings_file))
RuntimeError: Invalid settings file [settings]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/bin/song_recogniser", line 33, in <module>
    sys.exit(load_entry_point('abracadabra==0.1', 'console_scripts', 'song_recogniser')())
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/abracadabra/scripts/song_recogniser.py", line 37, in initialise
    storage.setup_db()
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/abracadabra/storage.py", line 26, in setup_db
    with get_cursor() as (conn, c):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Music_Similiarty/test/venv/lib/python3.10/site-packages/abracadabra/storage.py", line 18, in get_cursor
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

```

**Comment by magowiz** [comment]
same here

**Comment by MaestroKongrio** [comment]
try export PYTHONPATH="/project/path:$PYTHONPATH"
